//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RegistroAlumno.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class RegistroData : DbContext
    {
        public RegistroData()
            : base("name=RegistroData")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<alm_alumno> alm_alumno { get; set; }
        public virtual DbSet<grd_grado> grd_grado { get; set; }
        public virtual DbSet<mat_materia> mat_materia { get; set; }
        public virtual DbSet<mxg_materiasxgrado> mxg_materiasxgrado { get; set; }
    
        public virtual int CreateGrade(Nullable<int> idgrado, string grado_name)
        {
            var idgradoParameter = idgrado.HasValue ?
                new ObjectParameter("idgrado", idgrado) :
                new ObjectParameter("idgrado", typeof(int));
    
            var grado_nameParameter = grado_name != null ?
                new ObjectParameter("grado_name", grado_name) :
                new ObjectParameter("grado_name", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("CreateGrade", idgradoParameter, grado_nameParameter);
        }
    
        public virtual int CreateMateria(Nullable<int> mat_id, string mat_nombre)
        {
            var mat_idParameter = mat_id.HasValue ?
                new ObjectParameter("mat_id", mat_id) :
                new ObjectParameter("mat_id", typeof(int));
    
            var mat_nombreParameter = mat_nombre != null ?
                new ObjectParameter("mat_nombre", mat_nombre) :
                new ObjectParameter("mat_nombre", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("CreateMateria", mat_idParameter, mat_nombreParameter);
        }
    
        public virtual ObjectResult<GradoMateria_Result> GradoMateria()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GradoMateria_Result>("GradoMateria");
        }
    }
}
